defaults: &defaults
  shop:
    status_off_shelf: 0
    status_on_shelf: 1
    status_not_verify: 2
    status_verify_fail: 3

  promo:
    status_off_shelf: 0
    status_on_shelf: 1
    status_not_verify: 2
    status_verify_fail: 3

  coupon:
    status_unused: 0
    status_used: 1

  weixin_user:
    status_unsubscribe: 0
    status_subscribe: 1

    binding_none: 0
    binding_nick_name: 1
    binding_user_name: 2
    binding_mobile: 3
    binding_finish: 4

  send_coupon_to_mobile: true

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
