defaults: &defaults
  shop:
    status_off_shelf: 0
    status_on_shelf: 1

  promo:
    status_off_shelf: 0
    status_on_shelf: 1

  coupon:
    status_unused: 0
    status_used: 1

  weixin_user:
    status_unsubscribe: 0
    status_subscribe: 1

  send_coupon_to_mobile: true

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
